### ISSUE TITLE
[Feature Request] API for converting GMP large number to S21_DECIMAL

### ISSUE THREAD

**Issue by posidoni** [bezlant/s21_bigint#11]
Function `convert_gmp_to_decimal` is required to

**Tasks:**
- [x] Convert all  gmp integers to decimal (find way to get individual bits of GMP)
- [x] Get fractional part from gmp floats (see GMP docs & find special function)
- [x] Get rid of the fractional part by multiplying gmp float by 10
- [x] Get exponent from GMP float (this is the number of time we multiplied by 10)
- [x] Convert GMP integer to decimal (see step 1)

👨‍💻 [GMP docs](https://gmplib.org/manual/)

**Bonus:**
- [x] Write unit tests for unit testing API using different tool, i.e. GCC __int128

**Comment by posidoni** [comment]
I am working on this issue on branch `qa/add_tests`.  This will be used for testing `decimal sum`.

**Comment by posidoni** [comment]
Floats API: https://gmplib.org/manual/Initializing-Floats

**Comment by bezlant** [comment]
#

**Comment by bezlant** [comment]
GMP to decimal is implemented.

**Comment by posidoni** [comment]
@bezlant waiting for the review of #19 PR. It partially closes this issue.
