### ISSUE TITLE
[QA] Add edge cases for division

### ISSUE THREAD

**Issue by posidoni** [bezlant/s21_bigint#38]
# Division edge cases
**📋 Task**
- [x] Division with negative numbers
- [x] 0 / random_value
- [x] 0 / 0 (handle error gracefully)
- [x] Overflow / underflow cases (input stupidly large number & simply check code)

https://github.com/bezlant/int128_implementation/blob/64fe36dccd23a29e917a75ab77757f5b8f9de719/src/tests/math_tests/test_s21_div.c#L148

**Comment by posidoni** [comment]
Bug:

Division does not work correctly with negative numbers, because comparison logic inside binary division loop is not working as it was supposed to.

Theoretical Solution:
1. Inside binary division loop remove signs from arguments
2. Set the respective sign to 

This test can help reproduce the bug.
```
START_TEST(int32_t_negative1) {
    long long long_a = get_rand(1, 100000000);
    long long long_b = get_rand(1, 1000);

    if (1) {
        long_a *= -1;
    }

    if (0) {
        long_b *= -1;
    }

    int32_t a = long_a;
    int32_t b = long_b;
    int32_t div = a / b;
    s21_decimal res128 = {0};
    (void)s21_from_int_to_decimal(div, &res128);

    s21_decimal dec_a = ll_to_decimal(long_a);
    s21_decimal dec_b = ll_to_decimal(long_b);

#define DEBUG
#ifdef DEBUG
    printf("long_a  =%lld\n", long_a);
    printf("long_b  =%lld\n", long_b);
    printf("ll_to_decimal=\n");
    print_bits_r(dec_a);
    printf("dec_div=");
    printf("res128_=");
    print_bits_r(res128);
#endif

    s21_decimal dec_div = {0};
    s21_div(dec_a, dec_b, &dec_div);
    print_bits_r(dec_div);

    ck_assert_int_eq(s21_is_equal(res128, dec_div), TRUE);
}
END_TEST
}

```

**Comment by bezlant** [comment]
Pay attention to weird division like 941394913 / 0.0001 which turns into multiplication 941394913 * 10000. Those cases may cause overflow.
